feat(translation): add translation utils
thetreep/toolbox pull request #97
Opened 2024-12-10 15:38 UTC by fabianthetreep

2024-12-10 15:49 UTC, hectorj-thetreep requested changes

2024-12-10 15:49 UTC, hectorj-thetreep commented on translation/active.en.yaml
ca va être gênant d'avoir le catalogue de traduction dans la toolbox (donc dans les vendors)

2024-12-10 15:49 UTC, hectorj-thetreep commented on translation/active.en.yaml
il faut que la génération soit faite depuis le projet

2024-12-10 15:49 UTC, hectorj-thetreep commented on translation/gen.sh
> +goi18n extract -format yaml -sourceLanguage en ./../..
`./../..` ça marchait quand c'était dans `./internal/translator`

Là on va être dans `./vendor/github.com/thetreep/toolbox/translation`

2024-12-10 15:49 UTC, hectorj-thetreep commented on translation/gen.sh
> +goi18n extract -format yaml -sourceLanguage en ./../..
Il y a peut-être un moyen de récupérer la racine du projet de manière + safe (via `go` ?), mais je n'ai pas le temps de chercher là tout de suite

2024-12-24 08:42 UTC, fabianthetreep commented on translation/gen.sh
> +goi18n extract -format yaml -sourceLanguage en ./../..
`go list -m -f '{{.Dir}}'`

2025-01-08 15:15 UTC, merged

2025-01-10 09:55 UTC, hectorj-thetreep commented on translation/translate.go
> +var bundlesFS embed.FS
on va toujours charger le catalogue de test de la toolbox, pas celui généré pour le projet cible